name: samtools merge
description: Merge two bam files with samtools.
authors:
  - Johannes Köster
input:
  - list of bam files to merge
output:
  - merged bam file
notes: |
  * Samtools -@/--threads takes one integer as input. This is the number of additional threads and not raw threads.
