run:
  project: "SRR9824559"
  accession: accession.tsv

tools:
  sratoolkit: "/hpf/projects/CTrost/ajain/bacterial_genomics_pipeline/tools/sratoolkit.3.2.1-alma_linux64/bin"
  kraken2_db: "/hpf/projects/CTrost/ajain/bacterial_genomics_pipeline/tools/k2_standard"
  bakta_db: "/hpf/projects/CTrost/ajain/bacterial_genomics_pipeline/tools/db"