#!/bin/bash

#PBS -l walltime=72:00:00,nodes=1:ppn=4
#PBS -joe .
#PBS -d .
#PBS -l vmem=80g,mem=80g

if [ -z $pipeline ]; then pipeline=$1; fi;

if [ $pipeline = "wes" ]; then
	SF=~/crg2/cre.Snakefile; 
else
	SF=~/crg2/Snakefile
fi;

CP="/hpf/largeprojects/ccm_dccforge/dccdipg/Common/snakemake"

source /hpf/largeprojects/ccm_dccforge/dccdipg/Common/anaconda3/etc/profile.d/conda.sh
conda activate snakemake

snakemake --use-conda -s ${SF} --cores 4 --conda-prefix ${CP}
