#!/bin/bash

#PBS -l walltime=72:00:00,nodes=1:ppn=4
#PBS -joe .
#PBS -d .
#PBS -l vmem=80g,mem=80g

SF="/hpf/largeprojects/ccm_dccforge/dccdipg/Common/pipelines/crg2/Snakefile"
CP="/hpf/largeprojects/ccm_dccforge/dccdipg/Common/snakemake"

source /hpf/largeprojects/ccm_dccforge/dccdipg/Common/anaconda3/etc/profile.d/conda.sh
conda activate snakemake

snakemake --use-conda -s ${SF} --cores 4 --conda-prefix ${CP}
