#!/bin/bash

#PBS -l walltime=72:00:00,nodes=1:ppn=1
#PBS -joe .
#PBS -d .
#PBS -l vmem=30g,mem=30g
#PBS -N crg2_pbs


#usage: qsub dnaseq_cluster.pbs -v pipeline=wes 
#usage: qsub dnaseq_cluster.pbs -F "wgs"
#please change the following three variables according to your settings, as the recent crg2 repo is not copied over here

if [ -z $pipeline ]; pipeline=$1; fi;

if [ $pipeline = "wes" ]; then
	SF=~/crg2/cre.Snakefile; 
else
	SF=~/crg2/Snakefile
fi;

CP="/hpf/largeprojects/ccm_dccforge/dccdipg/Common/snakemake";
PBS=~/crg2/pbs_profile;

source /hpf/largeprojects/ccm_dccforge/dccdipg/Common/anaconda3/etc/profile.d/conda.sh
conda activate snakemake

snakemake --use-conda -s $SF --conda-prefix $CP  --profile $PBS -p  
