name: picard MarkDuplicates
description: |
  Mark PCR and optical duplicates with picard tools.
authors:
  - Johannes Köster
input:
  - bam file
output:
  - bam file with marked or removed duplicates
