name: picard AddOrReplaceReadGroups
description: Add or replace read groups with picard tools.
authors:
  - Johannes Köster
input:
  - bam file
output:
  - bam file with added or replaced read groups
