channels:
  - bioconda
  - conda-forge
dependencies:
  - python > 3.5.4
  - numpy==1.16.4
  - pandas==0.24.2
  - pysam==0.15.3
  - python-dateutil==2.8.0
  - pytz==2019.1
  - pyvcf==0.6.8
  - scipy==1.3.2
  - six==1.12.0
  - xlsxwriter==1.1.8
  - freebayes ==1.3.1