## the following <option>:<value> are defined in key_mapping.yaml file
## this file sets the rule specific values for the option
## options set here are availble under dict "job_properties["cluster"]" from within snakemake
## these options are handled in the scheduler.py script
##
## if you wish to add new <option>:<value>, you should
##  1. define the option and format string "{}" acceptable to the submission(qsub) command in key_mapping.yaml
##  2. set the value for the option in this file under __default__ or rule specific block
##  3. if needed, edit "scheduler.py" to handle the new options. By default, all options defined in 
##    "key_mapping.yaml" and set in this confif file are appended to the submission command. 
##
## option: value -> equivalent qsub paramater it sets
## name: "{rule}" -> -N {rule}
## mem: "20g" -> -l vmem=20g,mem=20g
## time: "15:00:00" -> -l walltime: 15:00:00
## mail: "ae" -> -m ae
## queue: "parallel" -> -q parallel
## threads: 7 -> -l nodes=1,ppn=7

__default__:
  name: "{rule}"
  mem: "20g"
  time: "20:00:00"
  join: True

map_reads:
  mem: "70g"
  time: "350:00:00"

remove_decoy:
  mem: "20g"

qualimap:
  mem: "70g"

manta:
  mem: "80g"

smoove:
  mem: "80g" 

snpeff:
  mem: 40gb

svscore:
  mail: "ae"
