channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bcbio-variation-recall=0.1.9
  - samtools=1.9
  - vt=2015.11.10
  - bcftools=1.9
  - bedtools=2.29.0
  - sambamba=0.5.9
  - vcflib=1.0.0
  - freebayes=1.3.1
  - platypus-variant=0.8.1.2
  - gatk4=4.1.4.1
