$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  run:
    type: object
    project:
      type: ["number", "string"]
    accession:
      type: ["number", "string"]
    required:
      - accession

  tools:
    type: object
    properties:
      sratoolkit:
        type: string
      kraken2_db:
        type: string
    required:
      - sratoolkit
      - kraken2_db