$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  run:
    type: object
    project:
      type: ["number", "string"]
    samples:
      type: ["number", "string"]
    units:
      type: string
    required:
      - samples
      - units

  ref:
    type: object
    properties:
      name:
        type: string
      no_decoy_name:
        type: string
      genome:
        type: string
      known-variants:
        type: string
    required:
      - genome

  filtering:
    type: object
    properties:
      vqsr:
        type: boolean
      hard:
        type: object
        properties:
          snvs:
            type: string
          indels:
            type: string
        required:
          - snvs
          - indels
    required:
      - vqsr
      - hard

  processing:
    type: object
    properties:
      mark-duplicates:
        type: boolean
      restrict-regions:
        type: string
      region-padding:
        type: integer
    required:
      - mark-duplicates

  annotation:
    type: object
    properties:
      vep:
        type: object
        properties:
          dir:
            type: string
          dir_cache:
            type: string
        required:
          - dir
          - dir_cache

  params:
    type: object
    properties:
      bwa:
        type: object
        properties:
          verbosity:
            type: string
          markSplitReads:
            type: string
          maxMem:
            type: string
        required:
          - markSplitReads

      gatk:
        type: object
        properties:
          HaplotypeCaller:
            type: string
          BaseRecalibrator:
            type: string
          GenotypeGVCFs:
            type: string
          VariantRecalibrator:
            type: string
        required:
          - HaplotypeCaller
          - BaseRecalibrator
          - GenotypeGVCFs
          - VariantRecalibrator

      picard:
        type: object
        properties:
          MarkDuplicates:
            type: string
        required:
          - MarkDuplicates

      qualimap:
        type: object
        properties:
          mem:
            type: string
          nw:
            type: integer
          c:
            type: string
          hm:
            type: integer
          extra:
            type: string
        required:
          - mem
          - nw
          - c

      verifybamid2:
        type: object
        properties:
          svd_prefix:
            type: string
          extra:
            type: string
        required:
          - svd_prefix

      snpeff:
        type: object
        properties:
          java_opts:
            type: string
        required:
          - java_opts

      svscore:
        type: object
        properties:
          operations:
            type: string
        required:
          - operations

    required:
      - gatk
      - picard
      - snpeff
      - svscore

required:
  - run
  - tools
  - ref
  - filtering
  - processing
  - annotation
  - params
